### ISSUE TITLE
How to increase battery level font size

### ISSUE THREAD

**Issue by mirko77** [micooke/LetsGetDigital#1]
I would like to increase the battery level font size

Any suggestion?

**Comment by micooke** [comment]
Yeah it's a little nasty.. You need to rebuild the font, then rebuild the icons and add them in. There's not an easy way to do this, it requires the font and exe in ```resources/font``` and then gimp or similar to combine the two bmps, then you have to manually configure the font settings so that it gets the icon characters from the right place with the right character..

**Comment by micooke** [comment]
On second thoughts, it's very nasty

**Comment by mirko77** [comment]
Ok thanks

**Comment by micooke** [comment]
Yeah sorry. It's not a "me" making life hard, the watch faces only reads the inbuilt garmin supplied fonts and alternate fonts are only via bitmaps
